DirectoryPath: "dist"
CheckExternal: true
CheckInternal: true
IgnoreCanonicalBrokenLinks: false
IgnoreAltMissing: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreURLs:
  - "drupal.org"  # Returns 403 to automated tools, works in browsers
  - "windowsupdate.microsoft.com"  # Windows Update client endpoint, not web-accessible
