DirectoryPath: "dist"
CheckExternal: true
CheckInternal: true
IgnoreCanonicalBrokenLinks: false
IgnoreAltMissing: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreURLs:
  - "drupal.org"
  - "onedrive.live.com"
  - "nytimes.com"
  - "inc.com"
  - "hhs.gov"
  - "parade.com"
  - "microsoft.com/en-us/store"
