DirectoryPath: "dist"
CheckExternal: true
CheckInternal: true
IgnoreCanonicalBrokenLinks: false
IgnoreAltMissing: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreURLs:
  - "onedrive.live.com"  # Bot detection, works in real browsers
  - "nytimes.com"  # Aggressive rate limiting, works in real browsers
  - "windowsupdate.microsoft.com"  # Windows Update client endpoint, not web-accessible
  - "drupal.org"  # Aggressive bot blocking, fails even with real browser headers
