import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, rmSync, unlinkSync, writeFileSync, readFileSync, rmdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

// Pure mode/argv logic lives in plain JS so the unit suite can cover it directly.
export { OVERWRITING_MODES, overwritesBaselines, argvRequestsSnapshotWrites } from './snapshot-guard-modes.mjs';

/**
 * Shared refusal for snapshot-writing runs on a host that doesn't match CI.
 *
 * Committed baselines are compared against CI's Ubuntu rendering, whose font stack
 * renders slightly taller than macOS, so snapshots written anywhere else overwrite
 * committed files with pixels CI will reject. Docker and CI are both Linux, so the
 * sanctioned baseline paths are unaffected.
 */
export const ALLOW_NATIVE_BASELINE = () => process.env.ALLOW_NATIVE_BASELINE === '1';

/**
 * Whether the write guards apply at all. Linux matches CI's rendering, and the env var
 * is the deliberate override.
 */
export const guardActive = () => process.platform !== 'linux' && !ALLOW_NATIVE_BASELINE();

/** Refuse a run that would overwrite baselines from a host that doesn't match CI. */
export const assertSnapshotWritesAllowed = (writesSnapshots: boolean) => {
	if (!writesSnapshots || !guardActive()) return;

	throw new Error(
		[
			`Refusing to write snapshots from a ${process.platform} host.`,
			'',
			"Committed baselines must match CI's Ubuntu rendering. Use:",
			'  npm run test:visual:baseline:docker',
			'',
			'To override anyway (only correct on a Linux host matching CI):',
			'  ALLOW_NATIVE_BASELINE=1 <command>',
		].join('\n')
	);
};

/**
 * The `missing` exception, closed.
 *
 * `missing` is Playwright's default, so it cannot be refused by mode without breaking
 * every ordinary run -- but it *does* write a host-rendered PNG when a visual assertion
 * has no baseline yet (a new or renamed test), and that file is committable. Mode alone
 * cannot distinguish "wrote nothing" from "created a baseline", so instead of guessing,
 * record the snapshot files before the run and compare after it.
 *
 * Files created during a guarded run are deleted rather than left in place: they are
 * seconds old, generated by the run itself, and the only correct way to produce them is
 * `npm run test:visual:baseline:docker`. Leaving them is exactly the path by which host
 * pixels reach the repository.
 */
const manifestPath = () => {
	// Keyed by pid as well as checkout: globalSetup and globalTeardown share one runner
	// process, but two concurrent runs from the same checkout would otherwise share one
	// manifest -- the second run's setup would clobber the first's list, and whichever
	// teardown ran first would delete the file, letting the other run's created
	// snapshots escape the check entirely.
	const key = createHash('sha256').update(process.cwd()).digest('hex').slice(0, 12);
	return join(tmpdir(), `astro-blog-snapshots-${key}-${process.pid}.json`);
};

const snapshotFilesUnder = (root: string): string[] => {
	const found: string[] = [];
	const walk = (dir: string, inSnapshotDir: boolean) => {
		let entries;
		try {
			entries = readdirSync(dir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			const full = join(dir, entry.name);
			if (entry.isDirectory()) {
				walk(full, inSnapshotDir || entry.name.endsWith('-snapshots'));
			} else if (inSnapshotDir) {
				found.push(full);
			}
		}
	};
	walk(root, false);
	return found.sort();
};

export const recordExistingSnapshots = (root: string) => {
	if (!guardActive()) return;
	const path = manifestPath();
	mkdirSync(tmpdir(), { recursive: true });
	writeFileSync(path, JSON.stringify(snapshotFilesUnder(root)), 'utf8');
};

export const assertNoSnapshotsCreated = (root: string) => {
	if (!guardActive()) return;
	const path = manifestPath();
	if (!existsSync(path)) return;

	const before = new Set<string>(JSON.parse(readFileSync(path, 'utf8')));
	rmSync(path, { force: true });

	const created = snapshotFilesUnder(root).filter((file) => !before.has(file));
	if (created.length === 0) return;

	// Only ever removes paths absent before this run started.
	for (const file of created) unlinkSync(file);
	// Drop the -snapshots directory too if the run was what created it. rmdirSync fails
	// on a non-empty directory, which is exactly the guard wanted: never touch a
	// directory that still holds committed baselines.
	for (const dir of new Set(created.map((file) => dirname(file)))) {
		try {
			rmdirSync(dir);
		} catch {
			/* still holds committed baselines -- leave it */
		}
	}

	throw new Error(
		[
			`Refusing to keep ${created.length} snapshot(s) written from a ${process.platform} host.`,
			'',
			'These had no baseline yet, so Playwright created them from this host\'s rendering,',
			"which does not match CI's Ubuntu font stack. They have been deleted:",
			...created.map((file) => `  ${file}`),
			'',
			'Generate them where they will match CI:',
			'  npm run test:visual:baseline:docker',
			'',
			'To keep host-rendered snapshots anyway (only correct on a Linux host matching CI):',
			'  ALLOW_NATIVE_BASELINE=1 <command>',
		].join('\n')
	);
};
